### PR TITLE
TC 01.3.1_03 <Header/Shopping Cart Modal Window> Display Empty Shopping Cart message

### PR DESCRIPTION
**Pull request by verafes**
TC - https://trello.com/c/KDdrnYsK

### CODE REVIEW

**Review by IrynaKolh — APPROVED** [review]
LGTM

**Review by S-Lanchik — APPROVED** [review]

**Review by Darren7711 — APPROVED** [review]
It's no necessary to create a variable for lacator if you use it only once.

**Review by ArinaJur — APPROVED** [review]
LGTM

**Comment by verafes** [comment]
Thank you!

**Comment by verafes** [comment]
> It's no necessary to create a variable for lacator if you use it only once.

Sure, however, this test, not a program. And I want to ensure to locate the element before asserting. So I know that the assertion fails, it's not because of a missing locator.

**Pull request merged**
