### PR TITLE
Mh/new branch

### PR DESCRIPTION
**Pull request by MariiaHolinko**

### CODE REVIEW

**Review by nadya0101 — COMMENTED** [review]
Please add link tor trello card and rename the pull request according to the rules

**Review by nadya0101 — APPROVED** [review]
Please add link for trello card and rename the pull request according to the rules

**Comment by MariiaHolinko** [comment]
[RF | header.spec | TC 10.3.1_01 Verify the Create an Account link is displayed on the main page in the header](https://trello.com/c/HBSjqHEW/599-rf-headerspec-tc-103101-verify-the-create-an-account-link-is-displayed-on-the-main-page-in-the-header)

**Comment by MariiaHolinko** [comment]
[RF | header.spec | TC 10.3.1_01 Verify the Create an Account link is displayed on the main page in the header](https://trello.com/c/HBSjqHEW/599-rf-headerspec-tc-103101-verify-the-create-an-account-link-is-displayed-on-the-main-page-in-the-header)

**Comment by MariiaHolinko** [comment]
[RF | header.spec | TC 10.3.1_01 Verify the Create an Account link is displayed on the main page in the header](https://trello.com/c/HBSjqHEW/599-rf-headerspec-tc-103101-verify-the-create-an-account-link-is-displayed-on-the-main-page-in-the-header)

**Comment by MariiaHolinko** [comment]
[RF | header.spec | TC 10.3.1_01 Verify the Create an Account link is displayed on the main page in the header](https://trello.com/c/HBSjqHEW/599-rf-headerspec-tc-103101-verify-the-create-an-account-link-is-displayed-on-the-main-page-in-the-header)

**Comment by MariiaHolinko** [comment]
https://trello.com/c/HBSjqHEW

**Pull request merged**
