### PR TITLE
TC 04.3.4_03 <Men page> Category block contains sub-categories: Tops and Bottoms which are links in blue text

### PR DESCRIPTION
**Pull request by yauheniumetski**
https://trello.com/c/4AlbLulA/298-tc-043403-men-page-sort-by-category-blocks-sub-categories-tops-and-bottoms-are-links-in-blue-text

### CODE REVIEW

**Comment by yauheniumetski** [comment]
[TC 04.3.4_03 <Men page> Category block contains sub-categories: Tops and Bottoms which are links in blue text](https://trello.com/c/4AlbLulA/298-tc-043403-men-page-category-block-contains-sub-categories-tops-and-bottoms-which-are-links-in-blue-text)

**Review by BabintsevaS — APPROVED** [review]

**Review by BabintsevaS — COMMENTED** [review]
in the test.describe name should be the same as a file name - 'menPage'

**Comment by yauheniumetski** [comment]
> in the test.describe name should be the same as a file name - 'menPage'
@BabintsevaS Hi! Could you explain why? On the page a lot of blocks and different US describe them. I could decompose pages on several test suits, and include different test suits in one-page file. Is it ok?

**Review by irinadash — APPROVED** [review]

**Comment by yauheniumetski** [comment]
@irinadash , Please, could you approve it again? Your approve is not active.

**Review by Sensation3000 — APPROVED** [review]

**Pull request merged**
