### PR TITLE
TC 04.4_04 <Menu/Gear> User able to see fitness equipment, bags, and watches when navigating from the Gear menu to the Gear page

### PR DESCRIPTION
**Pull request by yauheniumetski**
https://trello.com/c/SwdhgeJW/274-tc-04404-menu-gear-user-could-navigate-from-the-menu-to-the-gear-page

### CODE REVIEW

**Comment by yauheniumetski** [comment]
[TC 04.4_04 <Menu/Gear> User able to see fitness equipment, bags, and watches when navigating from the Gear menu to the Gear page](https://trello.com/c/SwdhgeJW/274-tc-04404-menu-gear-user-able-to-see-fitness-equipment-bags-and-watches-when-navigating-from-the-gear-menu-to-the-gear-page)

**Review by AlyonkaNY — APPROVED** [review]
LGTM

**Review by verafes — APPROVED** [review]

**Comment by alenavolakhava** [comment]
@yauheniumetski hi! as per the requirements, a pr should contain only one test case. in your case there are several. Please tag me whenever that's fixed so i can revisit

**Comment by yauheniumetski** [comment]
> @yauheniumetski hi! as per the requirements, a pr should contain only one test case. in your case there are several. Please tag me whenever that's fixed so i can revisit

Hi! Could you clarify? where is more than 1 test case in this PR?

**Review by alenavolakhava — APPROVED** [review]
looks good,
lgtm 

Screenshot 2024-04-17 at 9 40 06 AM

**Comment by yauheniumetski** [comment]
> looks good, lgtm
> 
> Screenshot 2024-04-17 at 9 40 06 AM

@alenavolakhava Thatks, a lot. I've just clarified to check. It's better to be sure that's everything ok)

**Pull request merged**
