### PR TITLE
TC 19.1.6_02 <Gear/Watches/Shopping Options/New> Apply filter New

### PR DESCRIPTION
**Pull request by Sandarella**
https://trello.com/c/395UdKQ8

### CODE REVIEW

**Review by AlyonkaNY — APPROVED** [review]
LGTM

**Review by Jul-Sol-RS — APPROVED** [review]
Все ок.

**Review by trukhachev495 — COMMENTED** [review]
окей

**Review by alenavolakhava — APPROVED** [review]
looks good to me!
Screenshot 2024-04-18 at 3 57 11 PM

**Pull request merged**
