### PR TITLE
RF | menPage.spec | Tops sub-category link led to the Tops-Men page & Bottoms sub-category link led to the Bottoms-Men page

### PR DESCRIPTION
**Pull request by yauheniumetski**
https://trello.com/c/uLMpGymf/412-rf-menpagespec-tops-sub-category-link-led-to-the-tops-men-page-bottoms-sub-category-link-led-to-the-bottoms-men-page

### CODE REVIEW

**Comment by yauheniumetski** [comment]
[RF | menPage.spec | Tops sub-category link led to the Tops-Men page & Bottoms sub-category link led to the Bottoms-Men page](https://trello.com/c/uLMpGymf/412-rf-menpagespec-tops-sub-category-link-led-to-the-tops-men-page-bottoms-sub-category-link-led-to-the-bottoms-men-page)

**Comment by yauheniumetski** [comment]
[RF | menPage.spec | Tops sub-category link led to the Tops-Men page & Bottoms sub-category link led to the Bottoms-Men page](https://trello.com/c/uLMpGymf/412-rf-menpagespec-tops-sub-category-link-led-to-the-tops-men-page-bottoms-sub-category-link-led-to-the-bottoms-men-page)

**Comment by yauheniumetski** [comment]
[ERR | menPage.spec | `${categoryItem} sub-category link led to the ${categoryItem}-Men page](https://trello.com/c/4YV75vLG/409-err-menpagespec-categoryitem-sub-category-link-led-to-the-categoryitem-men-page)

**Review by darin4 — APPROVED** [review]
ok

**Review by verafes — APPROVED** [review]

**Pull request merged**
