### PR TITLE
TC 04.4.4_04 Verify that the link Watches redirects to the Watches page

### PR DESCRIPTION
**Pull request by TupakAmaru13**
https://trello.com/c/1CXuEnbi/345-tc-044404-verify-that-the-link-watches-redirects-to-the-watches-page

### CODE REVIEW

**Review by BabintsevaS — COMMENTED** [review]
Did you notice that you have test.beforeEach, - it meats before each test runs the lane: await page.goto('/'); - each test will start with homepage.
In your test you want to start with particular page (Gear), it means test at first go to homepage, than go to Gear page - does it make sense? 
And one more question - are you sure that a user will be able to go directly to Gear page? Will be able to reach to Gear page without any trouble?

**Review by darin4 — APPROVED** [review]
Ok

**Comment by S-Lanchik** [comment]
Add link of Trello card

**Comment by S-Lanchik** [comment]
Please name your PR as TC

**Review by Rom-T — APPROVED** [review]

**Review by Rom-T — COMMENTED** [review]
Татьяна, исправьте пожалуйста перед мерджем комментарии оставленные. участниками

**Comment by TupakAmaru13** [comment]
@BabintsevaS I agree. Updated my test to go through the main page and links. @S-Lanchik Done. @Rom-T Done

**Comment by S-Lanchik** [comment]
Do not forget to put PR link to the trello card.

**Review by S-Lanchik — APPROVED** [review]

**Comment by TupakAmaru13** [comment]
[TC 04.4.4_04 Verify that the link Watches redirects to the Watches page](https://trello.com/c/1CXuEnbi/345-tc-044404-verify-that-the-link-watches-redirects-to-the-watches-page)

**Pull request merged**
