### PR TITLE
TC 02.2.1_01 User is redirected to Privacy Policy page

### PR DESCRIPTION
**Pull request by BabintsevaS**
https://trello.com/c/WXBulOTd/169-tc-022101-user-is-redirected-to-privacy-policy-page

### CODE REVIEW

**Review by verafes — COMMENTED** [review]
It's recommended to update main and create a new branch from the updated main. It seems that the previous test was removed and then committed again. Please ensure addon you test only. Thank you!

**Comment by BabintsevaS** [comment]
I added second test and did reformatting (код выровнялся правильно). There are 2 tests and all of them there!

**Comment by BabintsevaS** [comment]
> It's recommended to update main and create a new branch from the updated main. It seems that the previous test was removed and then committed again. Please ensure adding your test only. Thank you!

The previous test was NOT removed!

**Review by verafes — COMMENTED** [review]
Yes, it looks like. Sometimes VS code works tricky. ))) Please click 'Update branch' button here at the bottom.

**Comment by BabintsevaS** [comment]
> Yes, it looks like. Sometimes VS code works tricky. ))) Please click 'Update branch' button here at the bottom.

Done

**Review by verafes — APPROVED** [review]

**Review by andreinovikau92 — APPROVED** [review]

**Pull request merged**
