### PR TITLE
RF | productCard_WishList.spec | test name

### PR DESCRIPTION
**Pull request by OlgaPerepelitzki**
https://trello.com/c/D7uKCP74/450-rf-productcardwishlistspec-test-name

### CODE REVIEW

**Review by gudzenkoleruska — COMMENTED** [review]
all variables should be displayed within the test.describe or specific test, in this case the variable  "const itemName" it`s better to move in test.describe

**Comment by OlgaPerepelitzki** [comment]
> all variables should be displayed within the test.describe or specific test, in this case the variable "const itemName" it`s better to move in test.describe or test.beforeEach

Thank you for your comment. I need "const itemName" out of tests and out of tests and out of beforeEach. This const should be available in different  tests in this file. One of the tests is skip now. It will be open after refactoring

**Comment by gudzenkoleruska** [comment]
If you add this variable within the test.describe -> it will be available within all tests for this specific test.describe or are you planning to add more than 1 test.describe??

**Comment by OlgaPerepelitzki** [comment]
> If you add this variable within the test.describe -> it will be available within all tests for this specific test.describe or are you planning to add more than 1 test.describe??

I understand. Thanks. I will try to fix it

**Comment by OlgaPerepelitzki** [comment]
> If you add this variable within the test.describe -> it will be available within all tests for this specific test.describe or are you planning to add more than 1 test.describe??

I fix it. Can you review, please?

**Review by gudzenkoleruska — APPROVED** [review]

**Review by Eduard-QA — APPROVED** [review]

**Pull request merged**
