### PR TITLE
TC 04.4_02 <Menu/Gear> User could navigate from the menu to the next pages: Bags, Fitness equipment, Watches

### PR DESCRIPTION
**Pull request by yauheniumetski**
https://trello.com/c/zgQlE76U/218-tc-04402-menu-gear-user-could-navigate-from-the-menu-to-the-next-pages-bags-fitness-equipment-watches

### CODE REVIEW

**Comment by yauheniumetski** [comment]
[TC 04.4_02 <Menu/Gear> User could navigate from the menu to the next pages: Bags, Fitness equipment, Watches](https://trello.com/c/zgQlE76U/218-tc-04402-menu-gear-user-could-navigate-from-the-menu-to-the-next-pages-bags-fitness-equipment-watches)

**Comment by Sensation3000** [comment]
Hi, you have 3 tests in one PR
You should have only one test on one PR

Screenshot_20240415-144012_Drive

**Comment by yauheniumetski** [comment]
Comment is fixed

**Comment by Sensation3000** [comment]
Hi. Yeah, your code looks good. I'll approve it
But for me it is not identical to the TC. In the TC there is still 3 options where to click 

Maybe I am wrong, but I think there are two ways with this
1. On each test different tast cases.  That's a bit more of work of course

3. Your TC includes all three options, but that mean your one test should  be structured the way when all three are used. Like working with arrays and loops

Anyway  is your first tests and as I said I like your code. This probably to think in future

**Review by Sensation3000 — APPROVED** [review]

**Review by BabintsevaS — APPROVED** [review]

**Comment by yauheniumetski** [comment]
> Hi. Yeah, your code looks good. I'll approve it But for me it is not identical to the TC. In the TC there are still 3 options where to click
> 
> Maybe I am wrong, but I think there are two ways with this
> 
> 1. On each test different tast cases.  That's a bit more of work of course
> 2. Your TC includes all three options, but that mean your one test should  be structured the way when all three are used. Like working with arrays and loops
> 
> Anyway it is your first test and as I said I like your code. This probably to think in future

In the first variant, I decided to write separate tests for each variant. But in the next PR I'll rewrite it with loop/array

**Pull request merged**
